version: "3"
services:
    finalproject:
        build: ./
        image: finalproject
        container_name: finalproject
        ports:
            - "8000:8000"
        volumes:
            - "./finalproject:/app"
        command: "python manage.py runserver 0.0.0.0:8000"